apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYWdhcjE5OTMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVdSdGFVNHhNak0wIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson